# Generated by Django 2.0.2 on 2018-03-06 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('content_type', models.CharField(choices=[('DOCUMENT', 'Document'), ('VIDEO', 'Video')], default='DOCUMENT', max_length=200)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
