# Generated by Django 2.0.2 on 2018-05-03 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('page', models.CharField(choices=[('ABOUT', 'About'), ('CONTACT', 'Contact')], default='ABOUT', max_length=200)),
                ('priority', models.IntegerField()),
            ],
            options={
                'ordering': ['-priority'],
            },
        ),
    ]
