# Generated by Django 2.0.2 on 2018-03-18 15:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
