# Generated by Django 2.0.2 on 2018-03-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_altered_content_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(
                    choices=[('LANGUAGE', 'Language'), ('FRAMEWORK', 'Framework'), ('INTEGRATION', 'Integration')],
                    default='LANGUAGE', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='solution',
            name='tags',
            field=models.ManyToManyField(to='portfolio.Tag'),
        ),
    ]
