# Generated by Django 2.0.2 on 2018-03-21 17:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('portfolio', '0003_added_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['category', 'name']},
        ),
    ]
