# Generated by Django 2.0.2 on 2018-04-01 23:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('portfolio', '0004_altered_tag_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='description_only',
            field=models.BooleanField(default=False),
        ),
    ]
