# Generated by Django 2.0.2 on 2018-05-03 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_added_description_only'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solution',
            options={'ordering': ['-featured', 'description_only', '-release_date']},
        ),
    ]
